### ISSUE TITLE
Fix video and audio streaming

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#322]
Even after all the fixes already in place in our video player library, It has been reported in several issues that video and audio streaming has problems in the desktop client.

### Audio Streaming

Apparently the video streaming audio only works for a couple of seconds and then it stops, this was reported by several users at Discord.

### Video Streaming

Issue with the most information on the problem: 
- https://github.com/decentraland/explorer-desktop/issues/208

Other issues reporting the same problem:
- https://github.com/decentraland/explorer-desktop/issues/360
- https://github.com/decentraland/explorer-desktop/issues/279
- https://github.com/decentraland/issues/issues/494

Some coordinates in which the problem has been reported:
- 2, 55
- 110, -23
- -17, -122
- -22, 37
- -94,103
- -118,120

#### Approach

We'll try to solve the issue by integrating a unity plugin that apparently works with more formats than we can currently support on our own video player library. That task is tracked at 
- https://github.com/decentraland/explorer-desktop/issues/325

### Acceptance Criteria
- [ ] Finish [integrating video player library solution in unity](https://github.com/decentraland/explorer-desktop/issues/325) (and adding it to the building pipeline in a way that doesn't expose it as open-source since the plugin isn't open source)
- [ ] Have video and audio streaming working correctly in the reported scenes

**Comment by Jusdem** [comment]
Are there any updates on this, and how can we help?

**Comment by xavi-dcl** [comment]
@popuz this bug has been open for months. With the recent improvements to streaming, is it still relevant? If not, it would be great to verify and close this card.

**Comment by popuz** [comment]
hi @xavi-dcl . I was dealing with streaming in the browser which is a bit different. AVPro was on the @dalkia hands. However, we will probably need to discuss it together to sync video codecs and formats which we use (when uploading is fully on our side)

**Comment by dalkia** [comment]
Hi @xavi-dcl. We have implemented AVPro plugin in Desktop, and we didn't have a new report of videos not working there. This issue is safe to close.
Agreed with @popuz, we should set up that discussion.

**Comment by Jusdem** [comment]
I've tested this and the streaming still does not work on desktop client.
Please test with this: https://livepeercdn.com/recordings/b77ff043-132c-4804-81b2-3cf7dafe5767/index.m3u8
